# Generated by Django 4.0.2 on 2022-02-03 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('bar_code', models.CharField(max_length=48, primary_key=True, serialize=False, unique=True)),
                ('service_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('expiration_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('1', 'paid'), ('2', 'pending')], max_length=1)),
            ],
            options={
                'verbose_name': 'Payable',
                'verbose_name_plural': 'Payables',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=15)),
                ('card_number', models.CharField(blank=True, max_length=19, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_date', models.DateTimeField()),
                ('payable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payable')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
