# Generated by Django 4.0.2 on 2022-02-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transaction_payable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payable',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
